language: node_js
node_js:
  - '8'
cache: yarn

script:
  - yarn build && NODE_ENV=production yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output/
  keep_history: true
  name: TSUYUSATO "MakeNowJust" Kitsune
  email: make.just.on@gmail.com
  on:
    branch: master
