language: node_js
node_js:
  - '8'
cache: yarn

env:
  - NODE_ENV=production
script:
  - yarn build
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output/
  name: TSUYUSATO "MakeNowJust" Kitsune
  email: make.just.on@gmail.com
  on:
    branch: master
